# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_win:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Prepare Project
      run: |
        git submodule update --init --recursive
        mkdir build & cmd /c exit 0
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 ..
    - name: Build
      run: |
        cd build
        cmake --build . --config Release
    - name: Archive
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        filename: "Archive-Win.zip"
        path: build/Wahwth_artefacts/Release
        directory: build/Wahwth_artefacts
  build_mac:
        # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Prepare Project
      run: |
        git submodule update --init --recursive
        mkdir build & cmd /c exit 0
        cd build
        cmake -G "Xcode" ..
    - name: Build
      run: |
        cmake --build . --config Release
    - name: Archive
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        filename: "Archive-Mac.zip"
        path: build/Wahwth_artefacts/Release
        directory: build/Wahwth_artefacts
